name = "janno-portfolio"
main = "functions/api/auth.js"
compatibility_date = "2024-01-01"

[vars]
DISCORD_CLIENT_ID = "1409762260771012629"
DISCORD_CLIENT_SECRET = "rBArojdVSF2Dz6txO47YAAFXg07AZWOX"
DISCORD_REDIRECT_URI = "https://janno.pages.dev/auth/callback"

[[env.production]]
name = "janno-portfolio-prod"

[[env.staging]]
name = "janno-portfolio-staging"
