name = "janno-portfolio"
main = "functions/api/auth.js"
compatibility_date = "2024-01-01"

[vars]
DISCORD_CLIENT_ID = "YOUR_DISCORD_CLIENT_ID"
DISCORD_CLIENT_SECRET = "YOUR_DISCORD_CLIENT_SECRET"
DISCORD_REDIRECT_URI = "https://your-domain.com/auth/callback"

[[env.production]]
name = "janno-portfolio-prod"

[[env.staging]]
name = "janno-portfolio-staging"
